### ISSUE TITLE
training script

### ISSUE THREAD

**Issue by mhyeonsoo** [PuchatekwSzortach/combination_of_multiple_global_descriptors_for_image_retrieval#74]
Hi, thanks for the great resources.

I referred the ml.py to define a CGD model.

And now, I am trying to implement the data_loader with my custom dataset.

Can you provide a few guidance or a script for training with the custom dataset without using invoke() or something in the docker environment?
Thanks,

**Comment by PuchatekwSzortach** [comment]
`def train(...)` function defined in `net.invoke.ml` is your entry point for training models and following code there should answer all your questions. If you want me to help past that, you really need to be more specific.
